package br.com.wcorrea.seguranca;

public enum Permissoes {
    DESENVOLVEDOR,
    ADMINISTRADOR,
    ALTERAR_PERMISSOES_USUARIO,

    CLASSE_DESPESA_PESQUISAR, CLASSE_DESPESA_SALVAR, CLASSE_DESPESA_EXCLUIR,
    UNIVERSIDADE_PESQUISAR, UNIVERSIDADE_SALVAR, UNIVERSIDADE_EXCLUIR,
    ESTUDANTE_PESQUISAR, ESTUDANTE_SALVAR, ESTUDANTE_EXCLUIR;
}
