package br.com.wcorrea.seguranca;

public enum Permissoes {
    DESENVOLVEDOR,
    ADMINISTRADOR,

    CLASSE_DESPESA_SALVAR, CLASSE_DESPESA_EXCLUIR, CLASSE_DESPESA_PESQUISAR,
    UNIVERSIDADE_SALVAR, UNIVERSIDADE_EXCLUIR, UNIVERSIDADE_PESQUISAR;
}
